### ISSUE TITLE
Epiphany `yarn dist` fails on MacOS

### ISSUE THREAD

**Issue by flaschbier** [MattNer0/Epiphany#1]
Using `electron-builder 21.2.0` on MacOS (this is what you get when you are using Homebrew to install node and `npm install electron --save-dev` as indicated in the installation instructions for Electron as found in https://electronjs.org/docs/tutorial/installation). 

Receiving the following error when compiling Epiphany:
```
$ yarn dist
yarn run v1.19.0
...
  • packaging       platform=darwin arch=x64 electron=6.0.12 appOutDir=releases/mac
  ⨯ image ***/Epiphany/build/icons/icon_48x48@1x.png must be at least 512x512
error Command failed with exit code 1.
```

Web research shows that icon size is a well known issue with Electron, but solutions are not really within range for Electron-noobs. Just changing the size of `build/icons/icon_48x48@1x.png` to 512x512, however, made Epiphany compile and start up after installing the `.dmg`. The icon, however, looks awful now, so I won't create a pull request for the resized copy.

Could you please create a big enough icon from your original drawing to make Epiphany compile right away?

**Comment by MattNer0** [comment]
Hello!
Thank you for trying out Epiphany.
I was never able to test it on MacOS but I think I can change the "electron-builder.json" configuration so it loads a different icon.

**Comment by flaschbier** [comment]
confirmed.
Thanks a lot!
