### ISSUE TITLE
Very unfortunate location for notes

### ISSUE THREAD

**Issue by flaschbier** [MattNer0/Epiphany#2]
This is what I aim for:
- general notepad to put all my notes in, hopefully not as one big text file, but with some structure
- requiring plain text format for data safety and less dependency from any tool being maintained or ported to other platforms
- versioning of my notes in a git repository with suitable remotes for easy backup and distribution

From the description, I thought, Epiphany would be worth a try :)

This is what I did:
- compile Epiphany with `yarn dist`
- install via the `.dmg` I found in `<repo_root>/releases`
- opened Epiphany from the Applications menu

This is what I found:
- When Epiphany first comes up, it creates a `library` folder within `Macintosh HD⁩ ▸ ⁨Applications ▸ ⁨Epiphany.app⁩ ▸ ⁨Contents⁩ ▸ ⁨MacOS⁩` and places `epiphany.db` and a sample note there. 
- This is a very unfortunate place, because it will be difficult to backup notes from there. I would at least love to see it in a folder under my `$HOME`.
- I tried menu function "Move Library Directory", but the `.db` and the notes folders were not moved or even copied. Also new buckets and notes are still created under the original folder.

Could you please change the default folder for MacOS to, say, `$HOME/.epiphany` and/or make "Move Library Directory" work?

Versions:
- Epiphany `0.2.6`
- `electron-builder 21.2.0`
- `node v10.16.3`
 - MacOS `10.14.6 (18G84)`

**Comment by MattNer0** [comment]
My new commit should fix the "Move Library Directory" issue!

**Comment by flaschbier** [comment]
I write two issues before going out for dinner and when I come back, they are fixed. That's plainly awsome. Thanks a lot :D

On startup a popup now appears saying that no lib folder could be found and then "File" > "Select Library Directory" works and the choice is preserved cross closing Epiphany and reopening it. 

Maybe you want to bring up the "Select Library Directory" dialog right away when no folder is selected yet? Else feel free to close as confirmed.

**Comment by MattNer0** [comment]
You're very welcome!
I modified the missing library popup to open the picker dialog. Thank you for the suggestion.
Gonna close this now.
