### ISSUE TITLE
Keyboard shortcuts don't work on Mac

### ISSUE THREAD

**Issue by flaschbier** [MattNer0/Epiphany#3]
Hi @MattNer0,

more news re. Epiphany@Mac:
1. Keyboard shortcuts cmd-C/V/X/A are shown in the right click menu, but do not work. Instead ctrl-C/V/X/A do copypaste stuff.
2. cmd-Q does work, and so does the red closing dot on the upper left edge of the window, but they only close the main window, not the application (which then can be closed only via right-click in the system tray)
3. in display mode, I was not able to shortcut at all, only the right-click allows to copy stuff

Suggestions
- adapt the copypaste keyboard shortcuts to cmd-... on Mac, in both edit and display mode
- make cmd-Q and the "red dot" close the app, because it's a single window interactive foreground app and having it running without window does not make any sense

You see, I am using it... ;)
Cheers.

// updated to include the red dot thingy
// updated re. display mode

**Comment by MattNer0** [comment]
Done with most stuff. I'm gonna see about the display mode next.
And you should be able to change the close button behaviour with `tools -> reduce to tray`
